version: 1.0.{build}

branches:
  only:
  - master
nuget:
  project_feed: true
before_build:
- cmd: nuget restore TravelGuide.sln
build:
  project: TravelGuide.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal

environment:
  COVERALLS_REPO_TOKEN:
    secure: JP1SPyMZt9wSLYQ+xfnG3Gwv/mhm4Xp8FimSH8HjOyq2VLJiOg8s+1UaJanzQO/S

after_test: 
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"packages\NUnit.ConsoleRunner.3.6.0\tools\nunit3-console.exe" -targetargs:"/domain:single TravelGuide.Tests\bin\Debug\TravelGuide.Tests.dll" -output:coverage.xml

  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml