configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: JP1SPyMZt9wSLYQ+xfnG3Gwv/mhm4Xp8FimSH8HjOyq2VLJiOg8s+1UaJanzQO/S
before_build:
  - nuget restore
  
build:
  project: TravelGuide.sln
  verbosity: minimal
  publish_wap: true

after_test: 
        - TravelGuide\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]* -[TravelGuide]*" -target:"TravelGuide\packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single TravelGuide\TravelGuide.Tests\bin\Debug\TravelGuide.Tests.dll" -output:cover.xml

        - TravelGuide\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml